name: growth_game
description: Simple Game for Rigid Jam 2

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flame: 0.18.1
  flame_scrolling_sprite:  0.0.1

  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true
  assets:
    - assets/images/background.png
    - assets/images/ground.png
    - assets/images/remo.png
    - assets/images/remo_inflating.png
    - assets/images/remo_shrinking.png
    - assets/images/candy.png
    - assets/images/enemy.png
